#!/bin/sh

if [[ -f /tmp/$1 ]]; then 
    rm /tmp/$1
    notify-send "killed $1" &
    echo "killed $1" &
    pkill -f $1
else
    touch /tmp/$1 &
    # [[ "$1" == "vlc" ]] && prevDesktop=$(qdbus org.kde.KWin /KWin currentDesktop) && wmctrl -a vlc && qdbus org.kde.KWin /KWin setCurrentDesktop $prevDesktop &
    if [[ "$1" == "vlc" ]]; then
      playerctl -p vlc play-pause
    elif [[ "$1" == "discord" ]]; then
      wmctrl -c discord &
    else
      xdotool search --onlyvisible --classname --sync $1 windowminimize &
    fi
    sleep 1
    echo "time up for killing $1" &
    rm /tmp/$1 &
fi
