command W :execute ':silent w !sudo tee % > /dev/null' | :edit!
map Y y$
nnoremap ' `

nnoremap <A-j> :m .+1<CR>==
nnoremap <A-k> :m .-2<CR>==
inoremap <A-j> <Esc>:m .+1<CR>==gi
inoremap <A-k> <Esc>:m .-2<CR>==gi
vnoremap <A-j> :m '>+1<CR>gv=gv
vnoremap <A-k> :m '<-2<CR>gv=gv

nnoremap <C-j> 5jzz
nnoremap <C-k> 5kzz
nnoremap <C-l> :bnext<CR>
nnoremap <C-h> :bprev<CR>

filetype plugin on
filetype indent on
" set nocompatible
" set formatoptions-=ro
autocmd FileType * set formatoptions-=ro
set linebreak
set ignorecase
set noerrorbells
set hidden
set expandtab
set tabstop=2 softtabstop=2
set shiftwidth=2
set autoindent
set smartindent
set smarttab
set noswapfile
set wildignorecase
set scrolloff=3
set history=1000
set clipboard=unnamedplus
set lazyredraw
set splitbelow splitright
set incsearch
set termguicolors
set updatetime=300
set shortmess+=c
set completeopt=longest,menuone
" au BufEnter * set noro
set noro
set isfname+={,}
